routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\JsController;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [ArticleController::class, 'home'])->name('home');
Route::group([
    'prefix' => 'admin',
    'middleware' => 'auth'
], function () {
    Route::get('/',  [DashboardController::class, 'admin'])->name('admin.dashboard');
    Route::get('/dashboard',  [DashboardController::class, 'index'])->name('admin.dashboard');
});
Route::group(['middleware' => ['auth', 'role:ADMINISTRATEUR'], 'prefix' => 'admin'], function () {

    Route::group([
        'prefix' => 'articles'
    ], function ($router) {
        /**Articles Routes */
        Route::get('/validate', [ArticleController::class, 'admin_validate'])->name('articles.validate');
        Route::post('/validate/{article}/approve', [ArticleController::class, 'approve'])->name('articles.validate.approve');
        Route::post('/validate/{article}/reject', [ArticleController::class, 'reject'])->name('articles.validate.reject');
    });
});

Route::group(['middleware' => ['auth', 'role:UTILISATEUR'], 'prefix' => 'admin'], function () {


    Route::group([], function ($router) {
        /**Articles Routes */
        Route::resource('articles',   ArticleController::class);
    });
});




Route::get('/login', function () {
    return view('auth.login');
})->name('login');

Route::get('/password/reset', function () {
    return view('auth.login');
})->name('password.reset');

Route::name('js.')->group(function () {
    Route::get('dynamic.js',   [JsController::class, 'dynamic'])->name('dynamic');
});

Route::post('/login', [LoginController::class, 'login']);
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
Route::post('/register', [LoginController::class, 'register'])->name('register');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;
    protected $fillable =[
        'name',
        'category_id',
        'content',
        'image',
        'status',
        'user_id', 
    ];
     /**
     * Get the user that owns the article.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
     /**
     * Get the category that owns the article.
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Validator;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Symfony\Component\Console\Input\Input;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function home(Request $request)
    {
        $categories = Category::all();
        $articles = Article::where('status', 'approved')->get(); 
        return view('welcome', ['articles' => $articles, 'categories' =>  $categories]);
    }

    /**
     * Display a listing of the resource.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        /** @var \App\Models\User */
        $user = Auth::user();

        $status = $request->status;
        if (isset($status))
            $articles = $user->articles()->where('status', $status)->get();
        else  $articles = $user->articles()->get();
        $dashboard = [];
        $dashboard['drafts'] = $user->articles()->where('status', 'draft')->count();
        $dashboard['pendings'] = $user->articles()->where('status', 'pending')->count();
        $dashboard['approveds'] = $user->articles()->where('status', 'approved')->count();
        $dashboard['all'] = $user->articles()->count();
        return view('admin.article.index', ['articles' => $articles, 'status' => $status, 'dashboard' => $dashboard]);
    }

    /**
     * Display a listing of the resource.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function admin_validate(Request $request)
    {
        /** @var \App\Models\User */
        $user = Auth::user();

        $status = $request->status;
        if (isset($status))
            $articles = Article::where('status', $status)->get();
        else  $articles = Article::whereIn('status', ['rejected', 'pending', 'approved'])->get();
        $dashboard = [];
        $dashboard['rejecteds'] = Article::where('status', 'rejected')->count();
        $dashboard['pendings'] = Article::where('status', 'pending')->count();
        $dashboard['approveds'] = Article::where('status', 'approved')->count();
        $dashboard['all'] =  $dashboard['rejecteds']  +  $dashboard['pendings'] +    $dashboard['approveds'];
        return view('admin.article.validate', ['articles' => $articles, 'status' => $status, 'dashboard' => $dashboard]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.article.create', ['categories' => $categories, "article" => new Article()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validator = Validator::make($request->all(), [
            'name' => "required|string",
            'category_id' => "required|integer",
            'image' => 'required|mimes:jpeg,jpg,png,gif|required|max:10000',
            'status' => "required|string"
        ]);

        if ($validator->fails()) {
            return Redirect::back()
                ->withErrors($validator)
                ->withInput();
        }

        $inputs = $request->all();
        $article = new Article($inputs);
        $article->user_id = Auth::user()->id;
        $article->seo_name = "";
        $imageName = time() . '.' . $request->image->extension();

        $request->image->move(public_path('assets/img/articles'), $imageName);

        $article->image = 'assets/img/articles/' . $imageName;
        $article->save();
        return redirect()->route('articles.edit', ['article' =>  $article->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article =  Article::find($id);
        $categories = Category::all();
        return view('admin.article.edit', ['categories' => $categories, "article" => $article]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => "string",
            'category_id' => "integer",
            'status' => "string"
        ]);

        if ($validator->fails()) {
            return Redirect::back()
                ->withErrors($validator)
                ->withInput();
        }

        $inputs = $request->all();
        $article =   Article::find($id);
        $article->user_id = Auth::user()->id;
        $article->seo_name = "";
        if ($request->image) {
            $imageName = time() . '.' . $request->image->extension();

            $request->image->move(public_path('assets/img/articles'), $imageName);
            //TODO : Remove old image after upload

            $article->image = 'assets/img/articles/' . $imageName;
        }

        $article->update($inputs);
        return redirect()->route('articles.edit', ['article' =>  $article->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    /**
     * approve the article by admin.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function approve($id)
    {
        $article =  Article::find($id);
        $article->status = "approved";
        $article->save();
        return response()->json($article, 200);
    }


    /**
     * reject the article by admin.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function reject($id)
    {
        $article =  Article::find($id);
        $article->status = "rejected";
        $article->save();
        return response()->json($article, 200);
    }
}

resources/views/admin/article/create.blade.php
@extends('layouts.admin-master')

@section('title')
    Créer un nouveau article 
@endsection

@section('content')
  <style>
        .image-preview,
        #callback-preview {
            background-size: cover;
            background-position: center center;
        } 
    </style>
    <section class="section">
        <div class="section-header">
            <div class="section-header-back">
                <a href="features-posts.html" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Créer un nouveau article</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Article</a></div>
                <div class="breadcrumb-item">Créer un nouveau article</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Créer un nouveau article</h2>
            <p class="section-lead">
                Sur cette page, vous pouvez créer un nouveau article en remplissant tous les champs.
            </p>

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Écrivez votre article</h4>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('articles.store') }}" enctype="multipart/form-data"> 
                                @include('admin.article.form',['action'=>"create"]) 
                            </form>
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

@section('scripts')
    <script src="{{ asset('assets/modules/summernote/summernote-bs4.js') }}"></script>
    <script src="{{ asset('assets/modules/jquery-selectric/jquery.selectric.min.js') }}"></script>
    <script src="{{ asset('assets/modules/upload-preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
    <script src="{{ asset('assets/modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js') }}"></script>
    <script src="{{ asset('assets/js/page/features-post-create.js') }}"></script>
@endsection

resources/views/admin/article/edit.blade.php
@extends('layouts.admin-master')

@section('title')
    Edition de l'article {{ $article->name }}
@endsection

@section('content')
    <style>
        .image-preview,
        #callback-preview {
            background-size: cover;
            background-position: center center;
        }

    </style>
    <section class="section">
        <div class="section-header">
            <div class="section-header-back">
                <a href="features-posts.html" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Edition de l'article #{{ $article->id }}</h1>

            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="{{ route('articles.index') }}">Articles</a></div>
                <div class="breadcrumb-item">#{{ $article->id }}</div>
            </div>
        </div>

        <div class="section-body">
        
            <h2 class="section-title">Edition de l'article {{ $article->name }}</h2>
            <p class="section-lead">
                Sur cette page, vous pouvez editer l'article en changeant les valeurs souahitées.
            </p>
         
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header d-flex justify-content-between">
                            <h4>Modifier votre article</h4>
                            @include('admin.article.status',['status'=>$article->status])
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('articles.update', ['article' => $article->id]) }}"
                                enctype="multipart/form-data">
                                @method('PUT')
                                @include('admin.article.form',['action'=>"edit"])
                            </form>
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

@section('scripts')
    <script src="{{ asset('assets/modules/summernote/summernote-bs4.js') }}"></script>
    <script src="{{ asset('assets/modules/jquery-selectric/jquery.selectric.min.js') }}"></script>
    <script src="{{ asset('assets/modules/upload-preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
    <script src="{{ asset('assets/modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js') }}"></script>
    <script src="{{ asset('assets/js/page/features-post-create.js') }}"></script>
@endsection

resources/views/admin/article/form.blade.php
@csrf
<div class="form-group row mb-4">
    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
    <div class="col-sm-12 col-md-7">
        <input type="text" class="form-control" name="name" value="{{ $article->name }}">
    </div>
</div>
<div class="form-group row mb-4">
    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Catégorie</label>
    <div class="col-sm-12 col-md-7">
        <select class="form-control selectric" name="category_id">
            @foreach ($categories as $category)
                <option @if ($category->id == $article->category_id) selected="selected" @endif value="{{ $category->id }}">
                    {{ $category->name }}</option>
            @endforeach
        </select>
    </div>
</div>
<div class="form-group row mb-4">
    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Contenu</label>
    <div class="col-sm-12 col-md-7">
        <textarea class="summernote-simple" name="content">{{ $article->content }}</textarea>
    </div>
</div>
<div class="form-group row mb-4">
    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Thumbnail</label>
    <div class="col-sm-12 col-md-7">
        <div id="image-preview" class="image-preview" style="background-image: url('/{{ $article->image }}')">
            <label for="image-upload" id="image-label">Choose File</label>
            <input type="file" name="image" id="image-upload" />
        </div>
    </div>
</div>
<div class="form-group row mb-4">
    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tags</label>
    <div class="col-sm-12 col-md-7">
        <input type="text" class="form-control inputtags">
    </div>
</div>


<div class="form-group row mb-4">
    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
    <div class="col-sm-12 col-md-7 d-flex justify-content-between">
        @if ($action == 'create')
            <button type="submit" class="btn btn-danger" name="status" value="draft">Enregistrer</button>
            <button type="submit" class="btn btn-primary " name="status" value="pending">
                Enregistrer & Publier
            </button>
        @endif
        @if ($action == 'edit')
            <button type="submit" class="btn btn-danger" name="status"
                value="{{ $article->status }}">Enregistrer</button>
            @if ($article->status == 'draft')
                <button type="submit" class="btn btn-primary " name="status" value="pending">
                    Enregistrer & Publier
                </button>
            @endif
        @endif

    </div>
</div>

resources/views/admin/article/index.blade.php
@extends('layouts.admin-master')

@section('title')
    Mes Articles
@endsection

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Mes Articles</h1>
            <div class="section-header-button">
                <a href="{{ route('articles.create') }}" class="btn btn-primary"> Nouveau article</a>
            </div>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="{{ route('articles.index') }}">Articles</a></div>
                <div class="breadcrumb-item">Mes Articles</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Posts</h2>
            <p class="section-lead">
              Vous pouvez gérer toutes les publications, telles que l'édition, la suppression et plus encore.
            </p>

            <div class="row">
                <div class="col-12">
                    <div class="card mb-0">
                        <div class="card-body">

                            <ul class="nav nav-pills">
                                <li class="nav-item">
                                    <a class="nav-link @if (!isset($status)) active @endif" href="{{ route('articles.index') }}">Tous <span
                                            class="badge badge-white">{{ $dashboard['all'] }}</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link @if ($status=='draft' ) active @endif" href="{{ route('articles.index') }}?status=draft">Brouillon <span
                                            class="badge badge-danger">{{ $dashboard['drafts'] }}</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link @if ($status=='pending' ) active @endif"
                                        href="{{ route('articles.index') }}?status=pending">En attente de validation <span
                                            class="badge badge-primary">{{ $dashboard['pendings'] }}</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link @if ($status=='approved' ) active @endif"
                                        href="{{ route('articles.index') }}?status=approved">Publié(s) <span
                                            class="badge badge-success">{{ $dashboard['approveds'] }}</span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>All Posts</h4>
                        </div>
                        <div class="card-body">
                            <div class="float-left">
                                <select class="form-control selectric">
                                    <option>Action pour la sélection</option>
                                    <option>Déplacer vers brouillon</option>
                                    <option>Déplacer vers En attente</option>
                                    <option>Delete Pemanently</option>
                                </select>
                            </div>
                            <div class="float-right">
                                <form>
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                            <div class="clearfix mb-3"></div>

                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <tr>
                                        <th class="text-center pt-2">
                                            <div class="custom-checkbox custom-checkbox-table custom-control">
                                                <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad"
                                                    class="custom-control-input" id="checkbox-all">
                                                <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                                            </div>
                                        </th>
                                        <th>Titre</th>
                                        <th>Catégorie</th>
                                        <th>Auteur</th>
                                        <th>Créé à</th>
                                        <th>Statut</th>
                                    </tr>
                                    @foreach ($articles as $article)

                                        <tr>
                                            <td>
                                                <div class="custom-checkbox custom-control">
                                                    <input type="checkbox" data-checkboxes="mygroup"
                                                        class="custom-control-input" id="checkbox-2">
                                                    <label for="checkbox-2" class="custom-control-label">&nbsp;</label>
                                                </div>
                                            </td>


                                            <td>{{ $article->name }}
                                                <div class="table-links">
                                                    <a href="#">Afficher</a>
                                                    <div class="bullet"></div>
                                                    <a
                                                        href="{{ route('articles.edit', ['article' => $article->id]) }}">Editer</a>
                                                    <div class="bullet"></div>
                                                    <a href="#" class="text-danger">Déplacer vers brouillon</a>
                                                </div>
                                            </td>
                                            <td>
                                                <a href="#">{{ $article->category->name }}</a>
                                            </td>
                                            <td>
                                                <a href="#">
                                                    <img alt="image" src="{{ asset('assets/img/avatar/avatar-5.png') }}"
                                                        class="rounded-circle" width="35" data-toggle="title" title="">
                                                    <div class="d-inline-block ml-1">
                                                        {{ $article->user->firstname }} {{ $article->user->lastname }}
                                                    </div>
                                                </a>
                                            </td>
                                            <td> {{ $article->created_at->format('d/m/Y') }}</td>
                                            <td>
                                                @include('admin.article.status',['status'=>$article->status])
                                            </td>
                                        </tr>
                                    @endforeach

                                </table>
                            </div>
                            <div class="float-right">
                                <nav>
                                    <ul class="pagination">
                                        <li class="page-item disabled">
                                            <a class="page-link" href="#" aria-label="Previous">
                                                <span aria-hidden="true">&laquo;</span>
                                                <span class="sr-only">Previous</span>
                                            </a>
                                        </li>
                                        <li class="page-item active">
                                            <a class="page-link" href="#">1</a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link" href="#">2</a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link" href="#">3</a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link" href="#" aria-label="Next">
                                                <span aria-hidden="true">&raquo;</span>
                                                <span class="sr-only">Next</span>
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('scripts')
    <!-- JS Libraies -->
    <script src="{{ asset('assets/modules/jquery-selectric/jquery.selectric.min.js') }}"></script>

    <!-- Page Specific JS File -->
    <script src="{{ asset('assets/js/page/features-posts.js') }}"></script>
@endsection

resources/views/admin/article/status.blade.php
@if ($status == 'draft')
    <span class="badge badge-warning">Brouillon</span>
@endif
@if ($status == 'pending')
    <span class="badge badge-primary">En attente de validation</span>
@endif
@if ($status == 'approved')
    <span class="badge badge-success">Approuvé par l'admin</span>
@endif
@if ($status == 'rejected')
    <span class="badge badge-danger">Refusé par l'admin</span>
@endif